title: Changlan Liu's Homepage
page-top-title: Changlan
top-section-bg-text: Game AI & LLM Security
home-subtitle: Changlan Liu&ensp;|&ensp;刘长岚
copyright-text: '&copy; Changlan Liu 2026. All Rights Reserved.'
